### ISSUE TITLE
Handling of multiple contract addresses

### ISSUE THREAD

**Issue by davebryson** [pipermerriam/populus#272]
* Populus Version: 1.6.5
* OS: osx

When running a test I'm trying to deploy multiple instances of the same contract with different owners via:

`chain.provider.deploy_contract(...)`

However, I'm getting the expected Error:

`NotImplementedError:  Handling of multiple contract addresses has not been implemented`

Is there a potential work around for this now?  Is this a desired feature for the future?

**Comment by davebryson** [comment]
Great!

An interesting side note,  in the current approach if you do the following in a test:


`bobsContract = chain.provider.get_or_deploy_contract('Hello World', deploy_transaction={'from':bob})`

`aliceContract = chain.provider.get_or_deploy_contract('Hello World', deploy_transaction={'from':alice})`

All will appear like things are working.  But **Bob is actually the owner of Alice's contract** - so things won't show up unless you do explicit tests on functions.

You don't get the `NotImplemented` error until you call `chain.provider.deploy_contract(...)`

**Comment by pipermerriam** [comment]
@davebryson good you bring that up as it infers a point of confusion about the `get_or_deploy_contract` API.  The `deploy_transaction` parameter is only used if the contract is not already available.  I see how this might be confusing given that you are deploying with different arguments so in practice this is a different deploy.  This highlights a deficiency in how populus stores deloyed contract data that I'd like to address but I haven't quite figured out how to solve.

Working on a release for you.

**Comment by davebryson** [comment]
So I see the challenge with deployed contracts you're talking about.   When a contract is deployed it's stored in the backend keyed by the `name of the contract`.  Correct?    

I think truffle deals with this by writing the contract address to a generated version of the contract on deploy.  So the next time you call deploy for that contract, it checks to see if it has an address and goes from there.   If you call Contract.new()  it creates another instance, but you're responsible for the address.

If you keyed on the address vs. the contract name, that would solve the issue, but puts the responsibility back on the user to record the instance of the contract address they're interested in.

Maybe it's simpler to just put the recording of addresses for deployed contracts on the user.   This is something anyone will need to do when using web3 in the browser anyhow.

**Comment by pipermerriam** [comment]
FYI, this issue *should* be fixed in `1.6.6`.

**Comment by pipermerriam** [comment]
@davebryson if you're up for continuing the conversation about recording contract deploys....

One thing at play here may be that right now populus records deployments by default.  This may actually be the problem.

If recording addresses was changed to be explicit this might become a non-issue.

```
provider.deploy_contract('ContractA')  # doesn't record the address
provider.deploy_contract('ContractB', record_as='ContractB-v1')  # records it using the provided string.
```

Under this model it should *always* be clear to the user what the names should be to retrieve their contracts.

Thoughts?

**Comment by davebryson** [comment]
NOTE: Just adding my thoughts here, not criticizing your great work!  

That `record_as` would work.  But IMO, it's really the same as keeping track of the deployed address - now I need to remember the `record_as` value.

Since populus is not storing deployed information to disk (at least I don't think it is...).  This is all runtime information which can easily be tracked by the user...  In fact, there may be a benefit for modeling this like the web3 api that folks will use in the browser for DAPPs, as that will require them to maintain the address.


You can then do something like this and simplifying a lot of logic:

`instance = provider.deploy_contract(...)  # an instance has the address you can track` 

and

`c = provider.contract_at(instance.address) # grabs a already deployed one or error if not found...`

**Comment by pipermerriam** [comment]
> NOTE: Just adding my thoughts here, not criticizing your great work!

Consider your feedback valuable.  I don't like making software in a vacuum so knowing what you and others who use Populus think about it's API is important to me.

So I see where you are coming from in terms of allowing user's to provide their own addresses.  In that regard, I like idea for a new API `provider.contract_at` or maybe `provider.get_contract_at` to stay closer to the current naming convention.

There is however a need for Populus to keep record of certain deployment addresses in some manner.  This need is due to library linking.  When a user requests a contract which uses a library Populus needs to be able to link the underlying bytecode.  Having the user manually provide these addresses isn't a pleasant API (I've tried it).  Library dependencies can be deep, meaning that the dependency tree of libraries that a contract uses could be many levels deep meaning that the user would be required to somehow specify the addresses for this entire tree of libraries. 

The package management functionality that is currently in alpha makes heavy use of this functionality.  I also make heavy use of it in most of my Solidity codebases as I love using libraries.  If Populus doesn't keep track of this information then it quickly becomes "heavy" to deploy your contracts because you either have to A: redeploy all of your libraries, or B: provide all of the library linking information everytime you want to interact with your contracts.

I'm not sure I actually have a point that I'm working towards.  I hope this sheds a little light on the problem.  I'd of course love to hear any other thoughts or ideas you have on the subject.

Thanks for using Populus.  Let me know if you have any other problems.

Piper

**Comment by davebryson** [comment]
Ahhh... linking makes sense.   Where can I find the package management code that's in alpha?  Is that in a specific branch?

**Comment by pipermerriam** [comment]
https://github.com/pipermerriam/populus/tree/feat/v2

Installable as `2.0.0-alpha.4`
