### ISSUE TITLE
Documentation lacks examples accessing contracts by address

### ISSUE THREAD

**Issue by miohtama** [pipermerriam/populus#282]
* Populus Version: 1.6.6

### What was wrong?

Documentation does not tell how one can access an already deployed contract by its address.

**Comment by pipermerriam** [comment]
@miohtama if you know it's address then you *should* be able to simply get the factory and then instantiate it.

```python
MyFactory = chain.provider.get_contract_factory('MyFactory')
my_contract = MyFactory('0xabcdeadbeef12345....')
```

There are some caveats to this which are that it'll be using the ABI from the *current* state of that contract.  This is a design flaw that I'm aware of, and finally think I know how to fix.  Currently when deployments are recorded, they only record the address.  I'm looking to change that to record a more complete version of the compiled asset so that it's realistic to work with older versions of contracts.

What isn't clear to me yet is how one should go about accessing old versions of contracts. 

Does this in any way answer your question?

**Comment by miohtama** [comment]
Yes! This (current state) is exactly what I wanted. However it was unclear how to get there, as   examples deal only with contract identifies (not addresses).

**Comment by pipermerriam** [comment]
It's funny the things that I assume are obvious but are not.  Thanks for making me aware of this (and the pull requests that I'll look into on Monday)

**Comment by miohtama** [comment]
I will also make some PR. Can you open a new tutorial chapter "Code examples"?

**Comment by pipermerriam** [comment]
How about a completely new section titled something like *"Populus By Example"* which directly follows the tutorials..
