### ISSUE TITLE
Populus does not accept '0x' string into bytes32

### ISSUE THREAD

**Issue by avatar-lavventura** [pipermerriam/populus#297]
platform linux2 -- Python 2.7.12, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
plugins: populus-1.4.2
OS: Ubuntu

Populus does not accept `'0x7d5a99f603f231d53a4f39d1521f98d2e8bb279cf29bebfd0687dc98458e7f89' `as input into bytes32 parameter inside contract's function.

test.py:

`hello.example('0x7d5a99f603f231d53a4f39d1521f98d2e8bb279cf29bebfd0687dc98458e7f89') //does not work.`

hello.sol:

```
contract hello{
     function example(bytes32 in){
       } 
}
```

**Comment by pipermerriam** [comment]
This is an intentional design decision.  It's not possible to reliably infer that something is hex encoded so the method signatures should only accept string types.

If you have any suggestions on how this could be implemented I'm all ears but everything that's come to mind previously didn't sit well with me.
