### ISSUE TITLE
populus.contracts.exceptions.UnknownContract: No contract data was available for the contract identifier

### ISSUE THREAD

**Issue by Netherdrake** [pipermerriam/populus#341]
After upgrading from 1.6.9 to 1.9.1, the following test code raises an exception.

```
TokenFactory = chain.provider.get_contract_factory('Greeter')
```

Output:
```
    def get_base_contract_factory(contract_identifier, store_backends):
        for backend in store_backends.values():
            try:
                return backend.get_base_contract_factory(contract_identifier)
            except UnknownContract:
                pass
        else:
            raise UnknownContract(
                "No contract data was available for the contract identifier '{0}' "
>               "from any of the configured backends".format(contract_identifier)
            )
populus.contracts.exceptions.UnknownContract:
 No contract data was available for the contract identifier
```

_Meanwhile, `populus compile` works fine. Its just the tests that are failing._

![sad-puppy](https://user-images.githubusercontent.com/3516903/30039537-bdd1fd20-91d2-11e7-872d-8c68c485ceab.jpg)

**Comment by pipermerriam** [comment]
@Netherdrake can you give a little more information as to how your project is structured.  

I see your requesting the `'Greeter'` contract but assigning to `TokenFactory`.  Want to be sure that this isn't as simple as a mis-named variable.  Otherwise, can you give me a sense for the files in your `./contracts` directory and the contracts declared in them?  Also, can you call `chain.provider.get_all_contract_names()` and tell me the output?
