### ISSUE TITLE
Event/Log Tracking

### ISSUE THREAD

**Issue by RCL-Carl** [pipermerriam/populus#63]
How are you managing events/log outputs with this framework? I'm thinking that a sub-command called "eventlog" could be useful: 

```
$> populus eventlog --contract MyContract
{MyContract{0xbb348...}, topic=MyDummyEvent, data=["I generated an event"]}
{MyContract{0xbb348...}, topic=MyDummyEvent, data=["I generated another event"]}
```

As shown, eventlog command would start a new filter via RPC call and check for changes from the running geth chain. The user could pass a set of filters to this command so that only the events that they want to see would be printed out. With the above incantation, the "--contract" filter would allow this sub-command to only print event logs from the "MyContract" contract. Other filters would including the contract specific address, the topic itself (ie, what event name generated this), and possibly a filter on the data content. This is obviously not an exhaustive list. 

The user would launch this in a separate terminal, similar to the attach vs chain commands. 

The output above obviously is just an example, but it would show the contract, the address, the topic, and data for that particular event generation. I'm think that the user would be able to pass a format string (or reference a file with the appropriate config) that would determine what gets printed out. Alternatively, we could just print everything and expect the user to use sed or awk. 

Thoughts? Do you have anything in the works for this or no ?

**Comment by pipermerriam** [comment]
I don't have anything in the works but this has been an area that I've known needs attention.  The two methods on the event objects are barely useful and require you to do too much to retrieve the event data using them.

I'm supportive of the CLI feature, but I think I'd like to see it built on top of a solid python API so that the CLI portion is a thin wrapper on top of these features.  You won't be duplicating any work I'm doing in the area if you wanted to start into this.

**Comment by pipermerriam** [comment]
ok, this isn't a CLI feature, but all of this functionality is now implemented in `web3.py`
