### ISSUE TITLE
deploy, can I pass arguments ?

### ISSUE THREAD

**Issue by euri10** [pipermerriam/populus#82]
Suppose I have a contract with some parameters that can be passed in the constructor, how am I suppose to pass them within the framework ?
I posted on [http://ethereum.stackexchange.com/questions/2937/populus-how-do-i-deploy-a-contract-with-args-in-the-constructor](http://ethereum.stackexchange.com/questions/2937/populus-how-do-i-deploy-a-contract-with-args-in-the-constructor) as well, sorry if this is not the place on github but maybe someone may have the same interrogation one day and look here... dunno ;)

**Comment by pipermerriam** [comment]
Just a note about the stackoverflow question that references this issue.

http://ethereum.stackexchange.com/questions/2937/populus-how-do-i-deploy-a-contract-with-args-in-the-constructor/2963#2963

**Comment by euri10** [comment]
that was a lightning fast answer ! I'll try to think about ways to handle that, for testing purposes the hardcoding seems enough at first glance. thanks ;)

**Comment by pipermerriam** [comment]
## Implementation Ideas

### A: JSON file

`$ populus deploy MyContract --constructor-args some-json-file.json`

```javascript
// some-json-file.json
{
    MyContract: [1234, 'abcd']
}
```

* Nice because it's somewhat explicit and re-usable across deploys.
* Annoying because you will have various json files laying around.

### B: Command Line

`$ populus deploy MyContract:1234,abcd`

* Not very user friendly since it's somewhat verbose
* Might be awkward to parse and typecast the provided arguments.
* Won't be very nice if constructor arguments are things like long strings or contain characters that need to be escaped.

**Comment by euri10** [comment]
the json would get my token, it could maybe also be reusable in the web server part

**Comment by pipermerriam** [comment]
This is going to get implemented using a similar pattern to truffle migrations.

**Comment by pipermerriam** [comment]
Migrations are the tool that will fix this issue.  See #113
